name: note

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '10 */3 * * *' # Every 3 hours at minute 10

jobs:
  note:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.5
          extensions: mbstring

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Install agent-browser
        run: |
          npm install -g agent-browser
          npm ci --audit false
          npm i @sparticuz/chromium
          node ./scripts/install-chromium.js > /tmp/chromium_path.txt
          cat /tmp/chromium_path.txt

      - name: Run Command
        run: php artisan feedable:note
        env:
          SALVAGER_AGENT_BROWSER_PATH: "agent-browser"
          AGENT_BROWSER_EXECUTABLE_PATH: "/tmp/chromium"
          FEEDABLE_NOTE_TOKEN: ${{ secrets.FEEDABLE_NOTE_TOKEN }}
